//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace managementPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyectos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proyectos()
        {
            this.Tareas = new HashSet<Tareas>();
        }
    
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public int Completado { get; set; }
        public System.DateTime FechaComienzo { get; set; }
        public string Fase { get; set; }
        public decimal HorasNormales { get; set; }
        public decimal HorasEspeciales { get; set; }
        public decimal HorasReales { get; set; }
        public decimal HorasAnalisis { get; set; }
        public decimal HorasDesarrollo { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaDisenio { get; set; }
        public Nullable<System.DateTime> FechaValidacion { get; set; }
        public Nullable<System.DateTime> FechaEnVivo { get; set; }
        public Nullable<System.DateTime> FechaRecepcion { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string Cliente { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string JefeProyecto { get; set; }
        public string Consultor { get; set; }
        public string CodigoOferta { get; set; }
        public Nullable<int> Replanificaciones { get; set; }
        public Nullable<int> Incidencias { get; set; }
        public decimal Desviacion { get; set; }
        public decimal DesviacionDesarrollo { get; set; }
        public decimal DesviacionAnalisis { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tareas> Tareas { get; set; }
    }
}
