//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace managementPanel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tareas
    {
        public int IdTarea { get; set; }
        public int IdUsuario { get; set; }
        public string IdProyecto { get; set; }
        public string Titulo { get; set; }
        public Nullable<decimal> Horas { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string Estado { get; set; }
    
        public virtual Proyectos Proyectos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
